-- Migration: 20260507_item72_legal_thresholds
-- Ítem 72: Histórico de topes legales venezolanos por empresa.
--
-- SIN CAMBIOS DE ESQUEMA (ADR-057). Esta migración era un duplicado exacto de
-- 20260428_legal_threshold (mismo enum LegalThresholdType, misma tabla LegalThreshold,
-- mismos índices y FK; solo cambiaba el espaciado). Como `prisma migrate deploy` las aplica
-- en orden, repetir el historial desde cero (CI contra una BD vacía) fallaba aquí con
-- `type "LegalThresholdType" already exists`.
--
-- En producción ya está registrada como aplicada y su efecto es idéntico al de
-- 20260428_legal_threshold: el esquema resultante no cambia. Solo se vació el cuerpo para que
-- el historial sea repetible.
SELECT 1;
